apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-amd64
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels: { app: web-amd64 }
  template:
    metadata:
      labels: { app: web-amd64 }
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
          - containerPort: 80
